### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by realmeric** [HeemPlayz/Discord-Bot-Dashboard#3]
i started the project but when i click login button it says Invalid OAuth2 redirect_uri
Attachment(s):
https://pimps-need-to.get-some.help/4rdfgGJ.png

**Comment by RiftSTW** [comment]
Getting the same error too which really sucks

**Comment by HeemPlayz** [comment]
Sorry for late response, the solution is that you go to https://discord.com/developers
Then head to your bot
Next is you go to OAuth2
Finally you add the login URI in Redirect URIs example: https://example.com/auth

**Note**: you should add /auth after your domain so the login works.
**Note`**: you should edit the url in server.js, if you already did, then no worries.
